### ISSUE TITLE
Softlock during prologue?

### ISSUE THREAD

**Issue by strick0** [Truthkey/KH2FMRandomizer#18]
Whenever Roxas has to fight a Nobody without his keyblade, the game kills whatever heartless it spawns instead, making progression impossible. I have tried to re randomize the iso, and it still happens. If it helps figure out the issue, I am using Crazycatz's English patch (because I can't read Japanese)

**Comment by Similistorm** [comment]
I know right ? Unless a boss spawn,this one should be blacklisted. But it doesn't seem like the creator of the randomizer is gonna change this. I tried 6 differents run and I always get locked at this one because it's always a regular enemy who dies in a couple of hits.
Guess I'm gonna stick with the randomizer from YouTube.
