### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by keraps1996** [Truthkey/KH2FMRandomizer#22]
i've done what's written on the istruction. But i start the game,  and from the first battle it seems like the randomization is not installed.

**Comment by alextrimmer** [comment]
I am having the exact same issue. I'm not sure what the order is that we're supposed to do things.

**Comment by alextrimmer** [comment]
maybe you have to do stuff in the GUI first, then run it?

**Comment by alextrimmer** [comment]
Ok, I got it working but it's honestly not even worth it.
The Roxas prologue is completely effed up. There are a million chances to get locked out of the game.

**Comment by keraps1996** [comment]
what do you mean with getting locked out of the game?

**Comment by alextrimmer** [comment]
If you get a weak enemy for the fight where Roxas holds the bat, you'll kill the enemy and won't even be able to progress with the game as you need to hit a certain number of swings to trigger the custscene.
I would look up the garden of assemblage mod randomizer on YouTube, it's much better, safer, and well made. Been playing it nonstop since I installed it.

**Comment by warmech15** [comment]
So how did you get it working

**Comment by Truthkey** [comment]
It's what randomization has. You can get super hard enemies from the get go. I'm implementing a new function to disable enemy randomization in the prologue. In the future I will try to add a "Weak enemies in prologue".
